# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLikelihood_gaussian_subgroup_fiml_cpp <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_logLikelihood_gaussian_subgroup_fiml_cpp`, sigma, kappa, mu, fimldata, epsilon)
}

DWLS_wmat <- function(data, means, ncase, nvar) {
    .Call(`_psychonetrics_DWLS_wmat`, data, means, ncase, nvar)
}

WLS_wmat <- function(data, means, ncase, nvar) {
    .Call(`_psychonetrics_WLS_wmat`, data, means, ncase, nvar)
}

expected_hessian_fiml_Gaussian_group_cpp <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_expected_hessian_fiml_Gaussian_group_cpp`, sigma, kappa, mu, fimldata, epsilon)
}

fimlEstimator_Gauss_group_cpp <- function(sigma, kappa, mu, fimldata, epsilon, n) {
    .Call(`_psychonetrics_fimlEstimator_Gauss_group_cpp`, sigma, kappa, mu, fimldata, epsilon, n)
}

jacobian_fiml_gaussian_subgroup_sigma_cpp <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_jacobian_fiml_gaussian_subgroup_sigma_cpp`, sigma, kappa, mu, fimldata, epsilon)
}

covPrepare_cpp <- function(data, isOrdered, tol = 0.000001, WLSweights = TRUE, verbose = TRUE) {
    .Call(`_psychonetrics_covPrepare_cpp`, data, isOrdered, tol, WLSweights, verbose)
}

computeMean <- function(y) {
    .Call(`_psychonetrics_computeMean`, y)
}

computeThresholds <- function(y) {
    .Call(`_psychonetrics_computeThresholds`, y)
}

pearsonCov <- function(y1, y2, mean1, mean2, unbiased = FALSE) {
    .Call(`_psychonetrics_pearsonCov`, y1, y2, mean1, mean2, unbiased)
}

toOrdinal <- function(var) {
    .Call(`_psychonetrics_toOrdinal`, var)
}

cpp_table <- function(y1, y2) {
    .Call(`_psychonetrics_cpp_table`, y1, y2)
}

polychoric_fit_summary <- function(rho, tab, t1, t2) {
    .Call(`_psychonetrics_polychoric_fit_summary`, rho, tab, t1, t2)
}

binormal_density <- function(x1, x2, rho, sigma1 = 1.0, sigma2 = 1.0, mu1 = 0.0, mu2 = 0.0) {
    .Call(`_psychonetrics_binormal_density`, x1, x2, rho, sigma1, sigma2, mu1, mu2)
}

polychoric_grad_summary <- function(rho, tab, t1, t2) {
    .Call(`_psychonetrics_polychoric_grad_summary`, rho, tab, t1, t2)
}

estimate_polychoric <- function(y1, y2, t1, t2, tol = 0.000001, stepsize = 1, maxIt = 1000L, zeroAdd = 0.5) {
    .Call(`_psychonetrics_estimate_polychoric`, y1, y2, t1, t2, tol, stepsize, maxIt, zeroAdd)
}

threshold_grad_singlesubject <- function(y, j, t_aug) {
    .Call(`_psychonetrics_threshold_grad_singlesubject`, y, j, t_aug)
}

polychor_grad_singlesubject <- function(y1, y2, rho, t_aug1, t_aug2, pi) {
    .Call(`_psychonetrics_polychor_grad_singlesubject`, y1, y2, rho, t_aug1, t_aug2, pi)
}

bthreshold_grad_singlesubject <- function(y1, y2, rho, tIndex, t_aug1, t_aug2, pi) {
    .Call(`_psychonetrics_bthreshold_grad_singlesubject`, y1, y2, rho, tIndex, t_aug1, t_aug2, pi)
}

expHcpp <- function(states, probabilities, omega, tau, nstate, nvar) {
    .Call(`_psychonetrics_expHcpp`, states, probabilities, omega, tau, nstate, nvar)
}

expHessianCpp <- function(states, probabilities, omega, tau, beta, nstate, nvar) {
    .Call(`_psychonetrics_expHessianCpp`, states, probabilities, omega, tau, beta, nstate, nvar)
}

