# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fimlEstimator_Gauss_group_cpp <- function(sigma, kappa, mu, fimldata, n) {
    .Call(`_psychonetrics_fimlEstimator_Gauss_group_cpp`, sigma, kappa, mu, fimldata, n)
}

multiply <- function(A, B) {
    .Call(`_psychonetrics_multiply`, A, B)
}

rcpparma_hello_world <- function() {
    .Call(`_psychonetrics_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_psychonetrics_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_psychonetrics_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_psychonetrics_rcpparma_bothproducts`, x)
}

