# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eig_sym_cpp <- function(X) {
    .Call(`_psychonetrics_eig_sym_cpp`, X)
}

sympd_cpp <- function(X) {
    .Call(`_psychonetrics_sympd_cpp`, X)
}

solve_symmetric_cpp <- function(X, logdet = FALSE, epsilon = 1.490116e-08) {
    .Call(`_psychonetrics_solve_symmetric_cpp`, X, logdet, epsilon)
}

solve_symmetric_cpp_matrixonly <- function(X, epsilon = 1.490116e-08) {
    .Call(`_psychonetrics_solve_symmetric_cpp_matrixonly`, X, epsilon)
}

solve_symmetric_cpp_matrixonly_withcheck <- function(X, proper) {
    .Call(`_psychonetrics_solve_symmetric_cpp_matrixonly_withcheck`, X, proper)
}

bdiag_psychonetrics <- function(mats) {
    .Call(`_psychonetrics_bdiag_psychonetrics`, mats)
}

cbind_psychonetrics <- function(mats) {
    .Call(`_psychonetrics_cbind_psychonetrics`, mats)
}

vech <- function(X, diag = TRUE) {
    .Call(`_psychonetrics_vech`, X, diag)
}

seq_len_inds <- function(start, n) {
    .Call(`_psychonetrics_seq_len_inds`, start, n)
}

cov2cor_cpp <- function(X) {
    .Call(`_psychonetrics_cov2cor_cpp`, X)
}

wi2net_cpp <- function(X) {
    .Call(`_psychonetrics_wi2net_cpp`, X)
}

SDmat <- function(X) {
    .Call(`_psychonetrics_SDmat`, X)
}

invSDmat <- function(X) {
    .Call(`_psychonetrics_invSDmat`, X)
}

anyNon0 <- function(X) {
    .Call(`_psychonetrics_anyNon0`, X)
}

growlist <- function(X, Y) {
    invisible(.Call(`_psychonetrics_growlist`, X, Y))
}

parVector_cpp <- function(model) {
    .Call(`_psychonetrics_parVector_cpp`, model)
}

computePDC_cpp <- function(beta, kappa, sigma) {
    .Call(`_psychonetrics_computePDC_cpp`, beta, kappa, sigma)
}

blockToeplitz_cpp <- function(X) {
    .Call(`_psychonetrics_blockToeplitz_cpp`, X)
}

matrixform <- function(x) {
    .Call(`_psychonetrics_matrixform`, x)
}

kronecker_I_X <- function(X, n) {
    .Call(`_psychonetrics_kronecker_I_X`, X, n)
}

kronecker_X_I <- function(X, n) {
    .Call(`_psychonetrics_kronecker_X_I`, X, n)
}

kronecker_diag_sparse <- function(X) {
    .Call(`_psychonetrics_kronecker_diag_sparse`, X)
}

kronecker_diag <- function(X) {
    .Call(`_psychonetrics_kronecker_diag`, X)
}

Mmatrix_cpp <- function(parDF) {
    .Call(`_psychonetrics_Mmatrix_cpp`, parDF)
}

Mmatrix_cpp_list <- function(parDF) {
    .Call(`_psychonetrics_Mmatrix_cpp_list`, parDF)
}

formModelMatrices_cpp <- function(model) {
    .Call(`_psychonetrics_formModelMatrices_cpp`, model)
}

impliedcovstructures_cpp <- function(x, name = "", type = "cov", all = FALSE) {
    .Call(`_psychonetrics_impliedcovstructures_cpp`, x, name, type, all)
}

FisherInformation_inner_cpp_DSS <- function(estimator, model, manual) {
    .Call(`_psychonetrics_FisherInformation_inner_cpp_DSS`, estimator, model, manual)
}

FisherInformation_inner_cpp_DDS <- function(estimator, model, manual) {
    .Call(`_psychonetrics_FisherInformation_inner_cpp_DDS`, estimator, model, manual)
}

psychonetrics_FisherInformation_cpp_inner <- function(x, Fisher, model, useM = TRUE, sparsemodel = FALSE) {
    invisible(.Call(`_psychonetrics_psychonetrics_FisherInformation_cpp_inner`, x, Fisher, model, useM, sparsemodel))
}

psychonetrics_FisherInformation_cpp <- function(model, useM = FALSE, sparsemodel = FALSE) {
    .Call(`_psychonetrics_psychonetrics_FisherInformation_cpp`, model, useM, sparsemodel)
}

gradient_inner_cpp_DSS <- function(estimator, model, manual) {
    .Call(`_psychonetrics_gradient_inner_cpp_DSS`, estimator, model, manual)
}

gradient_inner_cpp_DDS <- function(estimator, model, manual) {
    .Call(`_psychonetrics_gradient_inner_cpp_DDS`, estimator, model, manual)
}

psychonetrics_gradient_cpp_inner <- function(x, grad, model, useM = FALSE, sparsemodel = FALSE) {
    invisible(.Call(`_psychonetrics_psychonetrics_gradient_cpp_inner`, x, grad, model, useM, sparsemodel))
}

psychonetrics_gradient_cpp <- function(x, model, useM = FALSE, sparsemodel = FALSE) {
    .Call(`_psychonetrics_psychonetrics_gradient_cpp`, x, model, useM, sparsemodel)
}

psychonetrics_fitfunction_cpp <- function(x, model) {
    .Call(`_psychonetrics_psychonetrics_fitfunction_cpp`, x, model)
}

impliedModel_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_impliedModel_cpp`, model, all)
}

prepareModel_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepareModel_cpp`, x, model)
}

logLikelihood_gaussian_subgroup_fiml_cpp_inner <- function(sigma, kappa, mu, dat, epsilon) {
    .Call(`_psychonetrics_logLikelihood_gaussian_subgroup_fiml_cpp_inner`, sigma, kappa, mu, dat, epsilon)
}

logLikelihood_gaussian_subgroup_fiml_cpp <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_logLikelihood_gaussian_subgroup_fiml_cpp`, sigma, kappa, mu, fimldata, epsilon)
}

logLikelihood_gaussian_subgroup_fiml_cpp_fullFIML <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_logLikelihood_gaussian_subgroup_fiml_cpp_fullFIML`, sigma, kappa, mu, fimldata, epsilon)
}

psychonetrics_optimizer <- function(model, lower, upper, optimizer = "L-BFGS-B") {
    .Call(`_psychonetrics_psychonetrics_optimizer`, model, lower, upper, optimizer)
}

expected_hessian_Gaussian_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_expected_hessian_Gaussian_group_cpp`, grouplist)
}

expected_hessian_Gaussian_cpp <- function(prep) {
    .Call(`_psychonetrics_expected_hessian_Gaussian_cpp`, prep)
}

maxLikEstimator_Gauss_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_maxLikEstimator_Gauss_group_cpp`, grouplist)
}

maxLikEstimator_Gauss_cpp <- function(prep) {
    .Call(`_psychonetrics_maxLikEstimator_Gauss_cpp`, prep)
}

maxLikEstimator_Ising_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_maxLikEstimator_Ising_group_cpp`, grouplist)
}

maxLikEstimator_Ising_cpp <- function(prep) {
    .Call(`_psychonetrics_maxLikEstimator_Ising_cpp`, prep)
}

jacobian_gaussian_sigma_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_jacobian_gaussian_sigma_group_cpp`, grouplist)
}

jacobian_gaussian_sigma_cpp <- function(prep) {
    .Call(`_psychonetrics_jacobian_gaussian_sigma_cpp`, prep)
}

jacobian_Ising_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_jacobian_Ising_group_cpp`, grouplist)
}

jacobian_Ising_cpp <- function(prep) {
    .Call(`_psychonetrics_jacobian_Ising_cpp`, prep)
}

DWLS_wmat <- function(data, means, ncase, nvar) {
    .Call(`_psychonetrics_DWLS_wmat`, data, means, ncase, nvar)
}

ULS_Gauss_exphes_pergroup_cpp <- function(grouplist) {
    .Call(`_psychonetrics_ULS_Gauss_exphes_pergroup_cpp`, grouplist)
}

expected_hessian_ULS_Gaussian_cpp <- function(prep) {
    .Call(`_psychonetrics_expected_hessian_ULS_Gaussian_cpp`, prep)
}

ULS_Gauss_cpp_pergroup <- function(grouplist) {
    .Call(`_psychonetrics_ULS_Gauss_cpp_pergroup`, grouplist)
}

ULS_Gauss_cpp <- function(prep) {
    .Call(`_psychonetrics_ULS_Gauss_cpp`, prep)
}

ULS_Gauss_gradient_pergroup_cpp <- function(grouplist) {
    .Call(`_psychonetrics_ULS_Gauss_gradient_pergroup_cpp`, grouplist)
}

ULS_gradient_Gauss_cpp <- function(prep) {
    .Call(`_psychonetrics_ULS_gradient_Gauss_cpp`, prep)
}

WLS_wmat <- function(data, means, ncase, nvar) {
    .Call(`_psychonetrics_WLS_wmat`, data, means, ncase, nvar)
}

expected_hessian_fiml_Gaussian_group_cpp_inner <- function(sigma, kappa, mu, dat, epsilon) {
    .Call(`_psychonetrics_expected_hessian_fiml_Gaussian_group_cpp_inner`, sigma, kappa, mu, dat, epsilon)
}

expected_hessian_fiml_Gaussian_group_cppversion <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_expected_hessian_fiml_Gaussian_group_cppversion`, sigma, kappa, mu, fimldata, epsilon)
}

expected_hessian_fiml_Gaussian_group_cpp_fullFIML <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_expected_hessian_fiml_Gaussian_group_cpp_fullFIML`, sigma, kappa, mu, fimldata, epsilon)
}

expected_hessian_fiml_Gaussian_cppVersion <- function(prep) {
    .Call(`_psychonetrics_expected_hessian_fiml_Gaussian_cppVersion`, prep)
}

fimlEstimator_Gauss_group_cpp_inner <- function(sigma, kappa, mu, dat, epsilon, n) {
    .Call(`_psychonetrics_fimlEstimator_Gauss_group_cpp_inner`, sigma, kappa, mu, dat, epsilon, n)
}

fimlEstimator_Gauss_group_cpp <- function(sigma, kappa, mu, fimldata, epsilon, n) {
    .Call(`_psychonetrics_fimlEstimator_Gauss_group_cpp`, sigma, kappa, mu, fimldata, epsilon, n)
}

fimlEstimator_Gauss_group_cpp_fullFIML <- function(sigma, kappa, mu, fimldata, epsilon, n) {
    .Call(`_psychonetrics_fimlEstimator_Gauss_group_cpp_fullFIML`, sigma, kappa, mu, fimldata, epsilon, n)
}

fimlestimator_Gauss_cpp <- function(prep) {
    .Call(`_psychonetrics_fimlestimator_Gauss_cpp`, prep)
}

jacobian_fiml_gaussian_subgroup_sigma_cpp_inner <- function(sigma, kappa, mu, dat, epsilon) {
    .Call(`_psychonetrics_jacobian_fiml_gaussian_subgroup_sigma_cpp_inner`, sigma, kappa, mu, dat, epsilon)
}

jacobian_fiml_gaussian_subgroup_sigma_cpp <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_jacobian_fiml_gaussian_subgroup_sigma_cpp`, sigma, kappa, mu, fimldata, epsilon)
}

jacobian_fiml_gaussian_subgroup_sigma_cpp_fullFIML <- function(sigma, kappa, mu, fimldata, epsilon) {
    .Call(`_psychonetrics_jacobian_fiml_gaussian_subgroup_sigma_cpp_fullFIML`, sigma, kappa, mu, fimldata, epsilon)
}

jacobian_fiml_gaussian_sigma_cpp <- function(prep) {
    .Call(`_psychonetrics_jacobian_fiml_gaussian_sigma_cpp`, prep)
}

covPrepare_cpp <- function(data, isOrdered, tol = 0.000001, WLSweights = TRUE, verbose = TRUE) {
    .Call(`_psychonetrics_covPrepare_cpp`, data, isOrdered, tol, WLSweights, verbose)
}

computeMean <- function(y) {
    .Call(`_psychonetrics_computeMean`, y)
}

computeThresholds <- function(y) {
    .Call(`_psychonetrics_computeThresholds`, y)
}

pearsonCov <- function(y1, y2, mean1, mean2, unbiased = FALSE) {
    .Call(`_psychonetrics_pearsonCov`, y1, y2, mean1, mean2, unbiased)
}

toOrdinal <- function(var) {
    .Call(`_psychonetrics_toOrdinal`, var)
}

cpp_table <- function(y1, y2) {
    .Call(`_psychonetrics_cpp_table`, y1, y2)
}

polychoric_fit_summary <- function(rho, tab, t1, t2) {
    .Call(`_psychonetrics_polychoric_fit_summary`, rho, tab, t1, t2)
}

binormal_density <- function(x1, x2, rho, sigma1 = 1.0, sigma2 = 1.0, mu1 = 0.0, mu2 = 0.0) {
    .Call(`_psychonetrics_binormal_density`, x1, x2, rho, sigma1, sigma2, mu1, mu2)
}

polychoric_grad_summary <- function(rho, tab, t1, t2) {
    .Call(`_psychonetrics_polychoric_grad_summary`, rho, tab, t1, t2)
}

estimate_polychoric <- function(y1, y2, t1, t2, tol = 0.000001, stepsize = 1, maxIt = 1000L, zeroAdd = 0.5) {
    .Call(`_psychonetrics_estimate_polychoric`, y1, y2, t1, t2, tol, stepsize, maxIt, zeroAdd)
}

threshold_grad_singlesubject <- function(y, j, t_aug) {
    .Call(`_psychonetrics_threshold_grad_singlesubject`, y, j, t_aug)
}

polychor_grad_singlesubject <- function(y1, y2, rho, t_aug1, t_aug2, pi) {
    .Call(`_psychonetrics_polychor_grad_singlesubject`, y1, y2, rho, t_aug1, t_aug2, pi)
}

bthreshold_grad_singlesubject <- function(y1, y2, rho, tIndex, t_aug1, t_aug2, pi) {
    .Call(`_psychonetrics_bthreshold_grad_singlesubject`, y1, y2, rho, tIndex, t_aug1, t_aug2, pi)
}

d_sigma_cholesky_cpp <- function(lowertri, L, C, In) {
    .Call(`_psychonetrics_d_sigma_cholesky_cpp`, lowertri, L, C, In)
}

d_sigma_delta_cpp <- function(L, delta_IminOinv, In, A) {
    .Call(`_psychonetrics_d_sigma_delta_cpp`, L, delta_IminOinv, In, A)
}

d_sigma_omega_cpp <- function(L, delta_IminOinv, A, delta, Dstar) {
    .Call(`_psychonetrics_d_sigma_omega_cpp`, L, delta_IminOinv, A, delta, Dstar)
}

d_sigma_kappa_cpp <- function(L, D, sigma) {
    .Call(`_psychonetrics_d_sigma_kappa_cpp`, L, D, sigma)
}

d_sigma_rho_cpp <- function(L, SD, A, Dstar) {
    .Call(`_psychonetrics_d_sigma_rho_cpp`, L, SD, A, Dstar)
}

d_sigma_SD_cpp <- function(L, SD_IplusRho, In, A) {
    .Call(`_psychonetrics_d_sigma_SD_cpp`, L, SD_IplusRho, In, A)
}

d_sigma_omega_corinput_cpp <- function(L, delta_IminOinv, A, delta, Dstar, IminOinv, In) {
    .Call(`_psychonetrics_d_sigma_omega_corinput_cpp`, L, delta_IminOinv, A, delta, Dstar, IminOinv, In)
}

d_sigma0_sigma_zeta_var1_cpp <- function(L, BetaStar, D2) {
    .Call(`_psychonetrics_d_sigma0_sigma_zeta_var1_cpp`, L, BetaStar, D2)
}

d_phi_theta_varcov_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_varcov_group_cpp`, grouplist)
}

d_phi_theta_varcov_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_varcov_cpp`, prep)
}

implied_varcov_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_varcov_cpp`, model, all)
}

prepare_varcov_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_varcov_cpp`, x, model)
}

d_mu_nu_lvm_cpp <- function(nu) {
    .Call(`_psychonetrics_d_mu_nu_lvm_cpp`, nu)
}

d_mu_nu_eta_lvm_cpp <- function(Lambda_BetaStar) {
    .Call(`_psychonetrics_d_mu_nu_eta_lvm_cpp`, Lambda_BetaStar)
}

d_mu_lambda_lvm_cpp <- function(nu_eta, BetaStar, In) {
    .Call(`_psychonetrics_d_mu_lambda_lvm_cpp`, nu_eta, BetaStar, In)
}

d_mu_beta_lvm_cpp <- function(nu_eta, lambda, tBetakronBeta) {
    .Call(`_psychonetrics_d_mu_beta_lvm_cpp`, nu_eta, lambda, tBetakronBeta)
}

d_sigma_lambda_lvm_cpp <- function(L, Lambda_BetaStar, Betasta_sigmaZeta, In, C) {
    .Call(`_psychonetrics_d_sigma_lambda_lvm_cpp`, L, Lambda_BetaStar, Betasta_sigmaZeta, In, C)
}

d_sigma_beta_lvm_cpp <- function(L, lambda, Betasta_sigmaZeta, Cbeta, Inlatent, tBetakronBeta) {
    .Call(`_psychonetrics_d_sigma_beta_lvm_cpp`, L, lambda, Betasta_sigmaZeta, Cbeta, Inlatent, tBetakronBeta)
}

d_sigma_sigma_zeta_lvm_cpp <- function(L, Lambda_BetaStar, Deta) {
    .Call(`_psychonetrics_d_sigma_sigma_zeta_lvm_cpp`, L, Lambda_BetaStar, Deta)
}

d_sigma_zeta_cholesky_lvm_cpp <- function(lowertri_zeta, L_eta, Cbeta, Inlatent) {
    .Call(`_psychonetrics_d_sigma_zeta_cholesky_lvm_cpp`, lowertri_zeta, L_eta, Cbeta, Inlatent)
}

d_sigma_zeta_kappa_lvm_cpp <- function(L_eta, Deta, sigma_zeta) {
    .Call(`_psychonetrics_d_sigma_zeta_kappa_lvm_cpp`, L_eta, Deta, sigma_zeta)
}

d_sigma_zeta_ggm_lvm_cpp <- function(L_eta, delta_IminOinv_zeta, Aeta, delta_zeta, Dstar_eta, Inlatent) {
    .Call(`_psychonetrics_d_sigma_zeta_ggm_lvm_cpp`, L_eta, delta_IminOinv_zeta, Aeta, delta_zeta, Dstar_eta, Inlatent)
}

d_sigma_epsilon_cholesky_lvm_cpp <- function(lowertri_epsilon, L, C_chol, In) {
    .Call(`_psychonetrics_d_sigma_epsilon_cholesky_lvm_cpp`, lowertri_epsilon, L, C_chol, In)
}

d_sigma_epsilon_kappa_lvm_cpp <- function(L, D, sigma_epsilon) {
    .Call(`_psychonetrics_d_sigma_epsilon_kappa_lvm_cpp`, L, D, sigma_epsilon)
}

d_sigma_epsilon_ggm_lvm_cpp <- function(L, delta_IminOinv_epsilon, A, delta_epsilon, Dstar, In) {
    .Call(`_psychonetrics_d_sigma_epsilon_ggm_lvm_cpp`, L, delta_IminOinv_epsilon, A, delta_epsilon, Dstar, In)
}

d_phi_theta_lvm_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_lvm_group_cpp`, grouplist)
}

d_phi_theta_lvm_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_lvm_cpp`, prep)
}

implied_lvm_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_lvm_cpp`, model, all)
}

prepare_lvm_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_lvm_cpp`, x, model)
}

d_mu_mu_var1_cpp <- function(beta) {
    .Call(`_psychonetrics_d_mu_mu_var1_cpp`, beta)
}

d_sigmastar_exo_cholesky_var1_cpp <- function(In, L, C, exo_cholesky) {
    .Call(`_psychonetrics_d_sigmastar_exo_cholesky_var1_cpp`, In, L, C, exo_cholesky)
}

d_sigma0_beta_var1_cpp <- function(BetaStar, In, sigma, C, L) {
    .Call(`_psychonetrics_d_sigma0_beta_var1_cpp`, BetaStar, In, sigma, C, L)
}

d_sigma_zeta_cholesky_var1_cpp <- function(lowertri_zeta, L, C, In) {
    .Call(`_psychonetrics_d_sigma_zeta_cholesky_var1_cpp`, lowertri_zeta, L, C, In)
}

d_sigma_zeta_kappa_var1_cpp <- function(L, D2, sigma_zeta) {
    .Call(`_psychonetrics_d_sigma_zeta_kappa_var1_cpp`, L, D2, sigma_zeta)
}

d_sigma_zeta_ggm_var1_cpp <- function(L, delta_IminOinv_zeta, A, delta_zeta, Dstar, In) {
    .Call(`_psychonetrics_d_sigma_zeta_ggm_var1_cpp`, L, delta_IminOinv_zeta, A, delta_zeta, Dstar, In)
}

d_sigma1_beta_var1_cpp <- function(IkronBeta, D2, Jb, sigma, beta, In) {
    .Call(`_psychonetrics_d_sigma1_beta_var1_cpp`, IkronBeta, D2, Jb, sigma, beta, In)
}

d_sigma1_sigma_zeta_var1_cpp <- function(IkronBeta, D2, Js) {
    .Call(`_psychonetrics_d_sigma1_sigma_zeta_var1_cpp`, IkronBeta, D2, Js)
}

d_phi_theta_var1_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_var1_group_cpp`, grouplist)
}

d_phi_theta_var1_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_var1_cpp`, prep)
}

implied_var1_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_var1_cpp`, model, all)
}

prepare_var1_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_var1_cpp`, x, model)
}

d_mu_lambda_dlvm1_cpp <- function(mu_eta, I_y) {
    .Call(`_psychonetrics_d_mu_lambda_dlvm1_cpp`, mu_eta, I_y)
}

d_sigmak_lambda_dlvm1_cpp <- function(lambda, k, allSigmas_within, C_y_eta, I_y, L_y, sigma_zeta_between) {
    .Call(`_psychonetrics_d_sigmak_lambda_dlvm1_cpp`, lambda, k, allSigmas_within, C_y_eta, I_y, L_y, sigma_zeta_between)
}

d_sigma0_sigma_zeta_within_dlvm1_cpp <- function(BetaStar, D_eta) {
    .Call(`_psychonetrics_d_sigma0_sigma_zeta_within_dlvm1_cpp`, BetaStar, D_eta)
}

d_sigma0_beta_dlvm1_cpp <- function(BetaStar, I_eta, allSigmas_within, C_eta_eta) {
    .Call(`_psychonetrics_d_sigma0_beta_dlvm1_cpp`, BetaStar, I_eta, allSigmas_within, C_eta_eta)
}

d_sigmak_beta_dlvm1_cpp <- function(J_sigma_beta, IkronBeta, k, allSigmas_within, I_eta) {
    .Call(`_psychonetrics_d_sigmak_beta_dlvm1_cpp`, J_sigma_beta, IkronBeta, k, allSigmas_within, I_eta)
}

d_sigmak_sigma_zeta_between_dlvm1_cpp <- function(lambda, D_eta) {
    .Call(`_psychonetrics_d_sigmak_sigma_zeta_between_dlvm1_cpp`, lambda, D_eta)
}

d_phi_theta_dlvm1_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_dlvm1_group_cpp`, grouplist)
}

d_phi_theta_dlvm1_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_dlvm1_cpp`, prep)
}

implied_dlvm1_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_dlvm1_cpp`, model, all)
}

prepare_dlvm1_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_dlvm1_cpp`, x, model)
}

d_mu_lambda_tsdlvm1_cpp <- function(mu_eta, I_y) {
    .Call(`_psychonetrics_d_mu_lambda_tsdlvm1_cpp`, mu_eta, I_y)
}

d_sigmak_lambda_tsdlvm1_cpp <- function(lambda, k, Sigma_eta_0, Sigma_eta_1, C_y_eta, I_y, L_y) {
    .Call(`_psychonetrics_d_sigmak_lambda_tsdlvm1_cpp`, lambda, k, Sigma_eta_0, Sigma_eta_1, C_y_eta, I_y, L_y)
}

d_sigma0_sigma_zeta_tsdlvm1_cpp <- function(BetaStar, D_eta) {
    .Call(`_psychonetrics_d_sigma0_sigma_zeta_tsdlvm1_cpp`, BetaStar, D_eta)
}

d_sigma0_beta_tsdlvm1_cpp <- function(BetaStar, I_eta, Sigma_eta_1, C_eta_eta) {
    .Call(`_psychonetrics_d_sigma0_beta_tsdlvm1_cpp`, BetaStar, I_eta, Sigma_eta_1, C_eta_eta)
}

d_sigma1_beta_tsdlvm1_cpp <- function(J_sigma_beta, IkronBeta, Sigma_eta_0, I_eta) {
    .Call(`_psychonetrics_d_sigma1_beta_tsdlvm1_cpp`, J_sigma_beta, IkronBeta, Sigma_eta_0, I_eta)
}

d_phi_theta_tsdlvm1_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_tsdlvm1_group_cpp`, grouplist)
}

d_phi_theta_tsdlvm1_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_tsdlvm1_cpp`, prep)
}

implied_tsdlvm1_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_tsdlvm1_cpp`, model, all)
}

prepare_tsdlvm1_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_tsdlvm1_cpp`, x, model)
}

d_phi_theta_meta_varcov_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_meta_varcov_group_cpp`, grouplist)
}

d_phi_theta_meta_varcov_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_meta_varcov_cpp`, prep)
}

implied_meta_varcov_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_meta_varcov_cpp`, model, all)
}

prepare_meta_varcov_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_meta_varcov_cpp`, x, model)
}

d_phi_theta_Ising_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_Ising_group_cpp`, grouplist)
}

d_phi_theta_Ising_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_Ising_cpp`, prep)
}

expHcpp <- function(states, probabilities, omega, tau, nstate, nvar) {
    .Call(`_psychonetrics_expHcpp`, states, probabilities, omega, tau, nstate, nvar)
}

expHessianCpp <- function(states, probabilities, omega, tau, beta, nstate, nvar) {
    .Call(`_psychonetrics_expHessianCpp`, states, probabilities, omega, tau, beta, nstate, nvar)
}

H <- function(state, graph, tau) {
    .Call(`_psychonetrics_H`, state, graph, tau)
}

Pot <- function(state, graph, tau, beta) {
    .Call(`_psychonetrics_Pot`, state, graph, tau, beta)
}

isingExpectation <- function(graph, tau, beta, responses) {
    .Call(`_psychonetrics_isingExpectation`, graph, tau, beta, responses)
}

computeZ_cpp <- function(graph, tau, beta, responses) {
    .Call(`_psychonetrics_computeZ_cpp`, graph, tau, beta, responses)
}

implied_Ising_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_Ising_cpp`, model, all)
}

prepare_Ising_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_Ising_cpp`, x, model)
}

d_phi_theta_ml_lvm_group_cpp <- function(grouplist) {
    .Call(`_psychonetrics_d_phi_theta_ml_lvm_group_cpp`, grouplist)
}

d_phi_theta_ml_lvm_cpp <- function(prep) {
    .Call(`_psychonetrics_d_phi_theta_ml_lvm_cpp`, prep)
}

implied_ml_lvm_cpp <- function(model, all = FALSE) {
    .Call(`_psychonetrics_implied_ml_lvm_cpp`, model, all)
}

prepare_ml_lvm_cpp <- function(x, model) {
    .Call(`_psychonetrics_prepare_ml_lvm_cpp`, x, model)
}

updateModel_cpp <- function(x, model, updateMatrices) {
    .Call(`_psychonetrics_updateModel_cpp`, x, model, updateMatrices)
}

addSEs_cpp <- function(xOld) {
    .Call(`_psychonetrics_addSEs_cpp`, xOld)
}

